name: worldy
description: "A new Flutter testcase project."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0-219.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  #network
  dio:

  #responsive
  flutter_screenutil:

  #state management
  provider:

  #dependency injection
  get_it:

  #local storage
  hive:
  hive_flutter:
  shared_preferences:

  intl:
  just_audio:
  flutter_launcher_icons:


dev_dependencies:
  hive_generator:
  build_runner:

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/































